### ISSUE TITLE
AttributeError: 'str' object has no attribute 'rule'py

### ISSUE THREAD

**Issue by azurism** [kevthehermit/PasteHunter#102]
I am seeing the following error when running Pastehunter-1.0. I am using Python 3.7.3 and Yara 3.11.0. The only thing I changed in settings.json is the elasticsearch output and I am currently using the default Yara rules. 

```
INFO:pastehunter.py:Starting PasteHunter Version: 1.0
INFO:pastehunter.py:Reading Configs
INFO:pastehunter.py:Logging to file disabled.
INFO:pastehunter.py:Setting Log Level to 20
INFO:pastehunter.py:Configure Inputs
INFO:pastehunter.py:Enabled Input: pastebin
INFO:pastehunter.py:Enabled Input: gists
INFO:pastehunter.py:Enabled Input: slexy
INFO:pastehunter.py:Configure Outputs
INFO:pastehunter.py:Enabled Output: elastic_output
INFO:pastehunter.py:Compile Yara Rules
INFO:pastehunter.py:Enable Blacklist Rules
INFO:pastehunter.py:Populating Queue
INFO:pastehunter.py:Fetching paste list from inputs.pastebin
INFO:pastehunter.py:Fetching paste list from inputs.gists
Process Process-5:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "pastehunter.py", line 185, in paste_scanner
    if match.rule == 'core_keywords' or match.rule == 'custom_keywords':
AttributeError: 'str' object has no attribute 'rule'
Process Process-4:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "pastehunter.py", line 185, in paste_scanner
    if match.rule == 'core_keywords' or match.rule == 'custom_keywords':
AttributeError: 'str' object has no attribute 'rule'
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "pastehunter.py", line 185, in paste_scanner
    if match.rule == 'core_keywords' or match.rule == 'custom_keywords':
AttributeError: 'str' object has no attribute 'rule'
INFO:gists.py:Remaining Limit: 4999. Resets at 2020-01-17T22:03:14
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "pastehunter.py", line 185, in paste_scanner
    if match.rule == 'core_keywords' or match.rule == 'custom_keywords':
AttributeError: 'str' object has no attribute 'rule'
INFO:pastehunter.py:Fetching paste list from inputs.slexy
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "pastehunter.py", line 185, in paste_scanner
    if match.rule == 'core_keywords' or match.rule == 'custom_keywords':
AttributeError: 'str' object has no attribute 'rule'
INFO:pastehunter.py:Added 440 Items to the queue
INFO:pastehunter.py:Sleeping for 300 Seconds

```

**Comment by Plazmaz** [comment]
Please try again with 1.2.1.

**Comment by azurism** [comment]
Any documentation on setting up 1.2.1? A lot has clearly changed.

**Comment by Plazmaz** [comment]
@azurism I've made some changes to our docs to give details on how to do this. For existing configs:
https://pastehunter.readthedocs.io/en/latest/migrating.html
You can read the basic setup guide here (pretty simple with pip): https://pastehunter.readthedocs.io/en/latest/installation.html#pip-installation

**Comment by Plazmaz** [comment]
Closing this as it's for an older version
