### ISSUE TITLE
input in flex scanner failed

### ISSUE THREAD

**Issue by ahezza** [kevthehermit/PasteHunter#109]
Since updating to the latest version, I am getting the following error when running pastehunter with custom YaraRules

```
Feb 17 17:10:30 [redacted] python3[18608]: ERROR:pastehunter-cli:Unable to Create Yara index: /opt/pastehunter/p
astehunter/YaraRules/custom(1): input in flex scanner failed
Feb 17 17:10:30 [redacted] python3[18608]: Traceback (most recent call last):
Feb 17 17:10:30 [redacted] python3[18608]:   File "/opt/pastehunter/pastehunter-cli", line 354, in main
Feb 17 17:10:30 [redacted] python3[18608]:     rules = yara.compile(filepaths=rule_files, externals={'filename':
 ''})
Feb 17 17:10:30 [redacted] python3[18608]: yara.SyntaxError: /opt/pastehunter/pastehunter/YaraRules/custom(1): i
nput in flex scanner failed
Feb 17 17:10:31 [redacted] systemd[1]: pastehunter.service: Service hold-off time over, scheduling restart.
Feb 17 17:10:31 [redacted] systemd[1]: pastehunter.service: Scheduled restart job, restart counter is at 5.
```

I've done a bit of Googling, doesn't seem like a common error.. Let me know if you need any more details.

**Comment by Plazmaz** [comment]
Hi, is "custom" a directory? Just from a quick Google it looks like Yara will throw that error when pointed at a directory instead of a file. "custom" should be a Yara file (you can use `include` statements for multiple files)

**Comment by ahezza** [comment]
@Plazmaz interestingly when I change the custom Yara field in the settings file to point at the file, I get the below error:

```
Feb 18 17:17:23 [redacted] python3[29901]: ERROR:pastehunter-cli:Unable to Create Yara index: [Errno 20] Not a directory: '/opt/pastehunter/pastehunter/YaraRules/custom/custom.yar'
Feb 18 17:17:23 [redacted] python3[29901]: Traceback (most recent call last):
Feb 18 17:17:23 [redacted] python3[29901]:   File "/opt/pastehunter/pastehunter-cli", line 351, in main
Feb 18 17:17:23 [redacted] python3[29901]:     conf['yara']['test_rules']
Feb 18 17:17:23 [redacted] python3[29901]:   File "/opt/pastehunter/pastehunter-cli", line 148, in yara_index
Feb 18 17:17:23 [redacted] python3[29901]:     for filename in os.listdir(custom_rules):
Feb 18 17:17:23 [redacted] python3[29901]: NotADirectoryError: [Errno 20] Not a directory: '/opt/pastehunter/pastehunter/YaraRules/custom/custom.yar'
Feb 18 17:17:24 [redacted] systemd[1]: pastehunter.service: Service hold-off time over, scheduling restart.
Feb 18 17:17:24 [redacted] systemd[1]: pastehunter.service: Scheduled restart job, restart counter is at 2.
Feb 18 17:17:24 [redacted] systemd[1]: Stopped PasteHunter.
Feb 18 17:17:24 [redacted] systemd[1]: pastehunter.service: Start request repeated too quickly.
Feb 18 17:17:24 [redacted] systemd[1]: pastehunter.service: Failed with result 'start-limit-hit'.
Feb 18 17:17:24 [redacted] systemd[1]: Failed to start PasteHunter.
```

I recall in the previous version that it required me to point at the directory rather than the file.

**Comment by Plazmaz** [comment]
Ack okay, I haven't looked at that code a ton yet. I'll dig into it when I get some time, seems like it's probably a bug. I don't think I changed any of that logic in the latest release though. Anyways, thanks for reporting, I'll get back to you!

**Comment by Plazmaz** [comment]
Oh my gosh I'm sorry I never got back to you! Okay so what's happening here is the config changed, so you'll just want to make '/opt/pastehunter/pastehunter/YaraRules/custom/custom.yar' '/opt/pastehunter/pastehunter/YaraRules/custom'
