### ISSUE TITLE
Timing out to 192.168.1.22

### ISSUE THREAD

**Issue by gn0sys** [kevthehermit/PasteHunter#47]
`ERROR:pastehunter.py:Unable to store Vp9hd6Pa to ConnectionError((<urllib3.connection.HTTPConnection object at 0x7f16044b0160>, 'Connection to 192.168.1.22 timed out. (connect timeout=10)')) caused by: ConnectTimeoutError((<urllib3.connection.HTTPConnection object at 0x7f16044b0160>, 'Connection to 192.168.1.22 timed out. (connect timeout=10)'))
PUT http://192.168.1.22:9200/paste-test-2018-42/paste/Tv33mSXj [status:N/A request:10.010s]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/connection/http_urllib3.py", line 115, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 333, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 146, in _new_conn
    (self.host, self.timeout))
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7f1605576438>, 'Connection to 192.168.1.22 timed out. (connect timeout=10)')
ERROR:pastehunter.py:Unable to store Tv33mSXj to ConnectionError((<urllib3.connection.HTTPConnection object at 0x7f1605576438>, 'Connection to 192.168.1.22 timed out. (connect timeout=10)')) caused by: ConnectTimeoutError((<urllib3.connection.HTTPConnection object at 0x7f1605576438>, 'Connection to 192.168.1.22 timed out. (connect timeout=10)'))
INFO:pastehunter.py:Sleeping for 300 Seconds
`

**Comment by kovacsbalu** [comment]
have you set it up `elastic_output` in `settings.json`?

**Comment by gn0sys** [comment]
It is set as enabled and is at the default value.

**Comment by kovacsbalu** [comment]
Yep, enabled but were do you run ELK? Which IP because 192.168.1.22 is the default value in example.

**Comment by coltbeck76** [comment]
set the elastic host to "localhost" and leave the rest default settings, if you haven't changed anything in elasticsearch configuration

**Comment by kevthehermit** [comment]
This has now been resolved in some pull, thanks to all who helped resolve
