### ISSUE TITLE
name 'q' is not defined

### ISSUE THREAD

**Issue by bismarkmarbles** [kevthehermit/PasteHunter#82]
I'm having trouble getting any output from the application. It adds items to the queue but throws a warning about processes.

F:\Scripts\[omitted]\PasteHunter>py pastehunter.py
INFO:pastehunter.py:Starting PasteHunter Version: 1.0
INFO:pastehunter.py:Reading Configs
INFO:pastehunter.py:Enabled Log File: logs/pastehunter.log
INFO:pastehunter.py:Setting Log Level to 10
INFO:pastehunter.py:Configure Inputs
INFO:pastehunter.py:Enabled Input: pastebin
INFO:pastehunter.py:Configure Outputs
INFO:pastehunter.py:Enabled Output: json_output
INFO:pastehunter.py:Enabled Output: csv_output
INFO:pastehunter.py:Enabled Output: smtp_output
INFO:pastehunter.py:Compile Yara Rules
INFO:pastehunter.py:Enable Blacklist Rules
INFO:pastehunter.py:Enable Test Rules
WARNING:pastehunter.py:Creating New Process
WARNING:pastehunter.py:Creating New Process
WARNING:pastehunter.py:Creating New Process
WARNING:pastehunter.py:Creating New Process
WARNING:pastehunter.py:Creating New Process
INFO:pastehunter.py:Populating Queue
INFO:pastehunter.py:Fetching paste list from inputs.pastebin
INFO:pastehunter.py:Starting PasteHunter Version: 1.0
INFO:pastehunter.py:Reading Configs
INFO:pastehunter.py:Enabled Log File: logs/pastehunter.log
INFO:pastehunter.py:Setting Log Level to 10
INFO:pastehunter.py:Configure Inputs
INFO:pastehunter.py:Enabled Input: pastebin
INFO:pastehunter.py:Configure Outputs
INFO:pastehunter.py:Starting PasteHunter Version: 1.0
INFO:pastehunter.py:Enabled Output: json_output
INFO:pastehunter.py:Reading Configs
INFO:pastehunter.py:Enabled Log File: logs/pastehunter.log
INFO:pastehunter.py:Setting Log Level to 10
INFO:pastehunter.py:Starting PasteHunter Version: 1.0
INFO:pastehunter.py:Configure Inputs
INFO:pastehunter.py:Enabled Output: csv_output
INFO:pastehunter.py:Starting PasteHunter Version: 1.0
INFO:pastehunter.py:Reading Configs
INFO:pastehunter.py:Enabled Input: pastebin
INFO:pastehunter.py:Reading Configs
INFO:pastehunter.py:Enabled Output: smtp_output
INFO:pastehunter.py:Configure Outputs
INFO:pastehunter.py:Enabled Log File: logs/pastehunter.log
INFO:pastehunter.py:Starting PasteHunter Version: 1.0
INFO:pastehunter.py:Enabled Log File: logs/pastehunter.log
INFO:pastehunter.py:Enabled Output: json_output
INFO:pastehunter.py:Setting Log Level to 10
INFO:pastehunter.py:Reading Configs
INFO:pastehunter.py:Setting Log Level to 10
INFO:pastehunter.py:Configure Inputs
INFO:pastehunter.py:Configure Inputs
INFO:pastehunter.py:Enabled Log File: logs/pastehunter.log
INFO:pastehunter.py:Enabled Input: pastebin
INFO:pastehunter.py:Enabled Input: pastebin
INFO:pastehunter.py:Setting Log Level to 10
INFO:pastehunter.py:Enabled Output: csv_output
INFO:pastehunter.py:Configure Outputs
INFO:pastehunter.py:Configure Outputs
INFO:pastehunter.py:Configure Inputs
INFO:pastehunter.py:Enabled Output: json_output
INFO:pastehunter.py:Enabled Output: json_output
INFO:pastehunter.py:Enabled Input: pastebin
INFO:pastehunter.py:Enabled Output: smtp_output
INFO:pastehunter.py:Configure Outputs
INFO:pastehunter.py:Enabled Output: json_output
INFO:pastehunter.py:Enabled Output: csv_output
INFO:pastehunter.py:Enabled Output: csv_output
INFO:pastehunter.py:Enabled Output: smtp_output
INFO:pastehunter.py:Enabled Output: csv_output
INFO:pastehunter.py:Enabled Output: smtp_output
INFO:pastehunter.py:Enabled Output: smtp_output
Process Process-2:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python36-32\lib\multiprocessing\process.py", line
 258, in _bootstrap
    self.run()
  File "C:\Program Files (x86)\Python36-32\lib\multiprocessing\process.py", line
 93, in run
    self._target(*self._args, **self._kwargs)
  File "F:\Scripts\[omitted]\PasteHunter\pastehunter.py", line 153, in paste_scanne
r
    if q.empty():
NameError: name 'q' is not defined
Process Process-4:
Process Process-1:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python36-32\lib\multiprocessing\process.py", line
 258, in _bootstrap
    self.run()
Process Process-3:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python36-32\lib\multiprocessing\process.py", line
 93, in run
    self._target(*self._args, **self._kwargs)
Process Process-5:
  File "C:\Program Files (x86)\Python36-32\lib\multiprocessing\process.py", line
 258, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "F:\Scripts\[omitted]\PasteHunter\pastehunter.py", line 153, in paste_scanne
r
    if q.empty():
  File "C:\Program Files (x86)\Python36-32\lib\multiprocessing\process.py", line
 93, in run
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python36-32\lib\multiprocessing\process.py", line
 258, in _bootstrap
    self.run()
NameError: name 'q' is not defined
  File "F:\Scripts\[omitted]\PasteHunter\pastehunter.py", line 153, in paste_scanne
r
    if q.empty():
  File "C:\Program Files (x86)\Python36-32\lib\multiprocessing\process.py", line
 258, in _bootstrap
    self.run()
  File "C:\Program Files (x86)\Python36-32\lib\multiprocessing\process.py", line
 93, in run
    self._target(*self._args, **self._kwargs)
NameError: name 'q' is not defined
  File "C:\Program Files (x86)\Python36-32\lib\multiprocessing\process.py", line
 93, in run
    self._target(*self._args, **self._kwargs)
  File "F:\Scripts\[omitted]\PasteHunter\pastehunter.py", line 153, in paste_scanne
r
    if q.empty():
  File "F:\Scripts\[omitted]\PasteHunter\pastehunter.py", line 153, in paste_scanne
r
    if q.empty():
NameError: name 'q' is not defined
NameError: name 'q' is not defined
DEBUG:pastehunter.py:Writing History
INFO:pastehunter.py:Added 196 Items to the queue

**Comment by Plazmaz** [comment]
@bismarkmarbles what was the issue/fix here? I've been experiencing the same issue and from what I can tell it is somehow related to how multiprocessing handles global variables on windows:
https://stackoverflow.com/questions/39095530/multiprocessing-does-not-see-global-variables

**Comment by bismarkmarbles** [comment]
@Plazmaz It could be related to that I'm not entirely sure.  I ended up stripping out multiprocessing all together.  I guess I could have tried to refactor it to work with multiprocessing but I'm only running it for pastebin at the moment so it's not terrible without it.

**Comment by Plazmaz** [comment]
Ah, okay. Yeah, we definitely want that multiprocessing. One easy fix is to move `q` out of the `if __name__ == 'main'` statement, and that seems to fix the issue, although I'm unsure what other impact that might have.

**Comment by bismarkmarbles** [comment]
@Plazmaz Thanks. I'll give that a shot!
